module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#1e2230',
          700: '#12141d',
          800: '#0b0c10',
          900: '#060709',
        },
        obsidian: {
          light:  '#1E2230',
          DEFAULT:'#12141D',
          dark:   '#0B0C10',
          darker: '#060709',
        },
        forest: {
          light:  '#1E2230',
          DEFAULT:'#12141D',
          dark:   '#0B0C10',
          darker: '#060709',
        },
        gold: {
          50:     '#FFFBEB',
          100:    '#FEF3C7',
          200:    '#FDE68A',
          300:    '#FCD34D',
          400:    '#FBBF24',
          500:    '#F59E0B',
          600:    '#D97706',
          700:    '#B45309',
          DEFAULT:'#F59E0B',
          dark:   '#D97706',
        },
        accent: {
          emerald: '#10B981',
          gold:    '#F59E0B',
          amber:   '#D97706',
          cyan:    '#06B6D4',
          rose:    '#F43F5E',
          blue:    '#3B82F6',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          2:       '#F8FAFC',
          3:       '#F1F5F9',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in':     'fadeIn 0.35s ease-out',
        'slide-up':    'slideUp 0.35s ease-out',
        'slide-right': 'slideInRight 0.3s ease-out',
        'scale-in':    'scaleIn 0.2s ease-out',
        'shimmer':     'shimmer 2s linear infinite',
        'float':       'float 3s ease-in-out infinite',
        'spin-slow':   'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn:       { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:      { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(-16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:      { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer:      { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        float:        { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
      },
      boxShadow: {
        'card':      '0 2px 16px rgba(0,0,0,0.06)',
        'card-hover':'0 6px 32px rgba(0,0,0,0.10)',
        'glow-green':'0 0 24px rgba(27,67,50,0.25)',
        'sidebar':   '4px 0 24px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
